### ISSUE TITLE
compatible with ES 6.2.2

### ISSUE THREAD

**Issue by shalinimonad** [jeskew/amazon-es-php#11]
AWS handler uses single index , how to create multiple index with multiple type  and how laravel scout would know in which index need  to import type.I m using laravel 5.5 , AWS ES instance 6.2.2 .
Scout only importing one model.
 Any idea ?

**Comment by apokryfos** [comment]
I'm curious as to what gave you the impression that the handler uses an index?

**Comment by shalinimonad** [comment]
Actually i got confused with usage section  

// Use the client as you normally would
$client->index([
    'index' => $index,
    'type' => $type,
    'id' => $id,
    'body' => [$key => $value]
]);

I have updated scout to create multiple index ,so closing this
