### ISSUE TITLE
Release new version - 0.2.4

### ISSUE THREAD

**Issue by bastuijnman** [jeskew/amazon-es-php#15]
Hi, 

Would you be able to release a version `0.2.4` to packagist? Would be nice to be able to use this fix:
https://github.com/jeskew/amazon-es-php/issues/12

So far we've been running on the forked version, but it would be nice to run on the original package of course 😃 

Cheers,

Bas Tuijnman
24i

**Comment by IllyaMoskvin** [comment]
It's been a bit, so pinging @jeskew and bumping this topic. Our current work-around is to specify this git repository as a source in our project's `composer.json`. Assuming that you've run this:

```
composer require jsq/amazon-es-php
```

Change this:

```
{
    "require": {
        "jsq/amazon-es-php": "^0.2.3"
    }
}
```

...to this:


```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jeskew/amazon-es-php.git"
        }
    ],
    "require": {
        "jsq/amazon-es-php": "dev-master"
    }
}
```
...and run this:

```
composer update jsq/amazon-es-php
```

**Comment by jeskew** [comment]
https://github.com/jeskew/amazon-es-php/commit/6f1ae9044c25c69b9c706ecb0906b45574cae589 has been tagged as v0.3.0
