### ISSUE TITLE
use of AWS ECS task iam role

### ISSUE THREAD

**Issue by ebarault** [jeskew/amazon-es-php#16]
Hi,

Does the bundle support ECS task iam roles as described in the following reference ?
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

The aws php sdk supports it by looking for the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` env var. 

If you implementation relies on the aws php sdk to retrieve credentials, i think it should work out of the box. Did you try?

**Comment by jeskew** [comment]
This package uses the SDK’s default credential provider, so ECS task roles should work in the same way.
