### ISSUE TITLE
Trailing slashes on hosts cause invalid uri exceptions

### ISSUE THREAD

**Issue by timoschinkel** [jeskew/amazon-es-php#17]
I am not sure whether this should be fixed by sanitizing the host uris in https://github.com/elastic/elasticsearch-php or that this library should (also) handle this. But since the exception is thrown in this library I will create the issue in this repository.

We noticed this issue when creating a new Elasticsearch cluster on AWS and copying the endpoint uri from the Amazon Console. That uri contains a trailing slash.

### Reproduction scenario

```php
$handler = new \Aws\ElasticsearchService\ElasticsearchPhpHandler(
    'eu-west-1', 
    CredentialProvider::defaultProvider()
);
$client = \Elasticsearch\ClientBuilder::fromConfig([
    'hosts' => ['http://host.docker.internal:9200/'], 
    'handler' => $handler
], true);

$client->info()
```

This will lead to an `InvalidArgumentException` with the message "'Unable to parse URI: //'" to be triggered in the creation of a PSR-7 request at https://github.com/jeskew/amazon-es-php/blob/b2b5634e4662f5d620891bda9b6d0af73954043c/src/ElasticsearchPhpHandler.php#L63

The path of the uri is `/`, to get the information of the host `/` is added and thus the uri becomes `//`, which in itself is an invalid uri. I have only seem this issue occur with this operation, since the other operations add something to the path resulting in uris like `//my_index`. Those uris *are* excepted by the `Uri` constructor. 

Maybe the best solution is to sanitize the host uris in https://github.com/elastic/elasticsearch-php by removing trailing slashes - I will try to raise an issue at that repository as well - or maybe this should also be handled in this repository.

Edit: issue on `elastic/elasticsearch-php`: https://github.com/elastic/elasticsearch-php/issues/869

### System details
- PHP 7.2
- `jsq/amazon-es-php` version `0.2.3` (latest stable)
- `elasticsearch/elasticsearch` version `6.1.0` (latest stable)
- OS: standard `php:7.2-fpm` Docker container

**Comment by jeskew** [comment]
As mentioned in elastic/elasticsearch-php#869, Elasticsearch-PHP expects hosts to be specified without a trailing slash. I don't think an ElasticsearchService instance would accept a request with a signed host header that ended in a trailing slash, so I'm not sure a valid request would be produced even if the `uri` portion of the request were sanitized on line 63.
