### ISSUE TITLE
Create anonymous client

### ISSUE THREAD

**Issue by joeworganic** [jeskew/amazon-es-php#18]
Is it possible to create an anonymous client, as per this example: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_anonymous.html

Any help would be appreciated

**Comment by jeskew** [comment]
This library does not support anonymous clients, but its only role is to sign requests generated and sent by the elasticsearch-php library. Omitting this handler from an elasticsearch-php client will create an anonymous client.
