### ISSUE TITLE
Compatibility with Opensearch-php

### ISSUE THREAD

**Issue by remyflier** [jeskew/amazon-es-php#25]
Is there any value in making this package compatible with [opensearch-php](https://github.com/opensearch-project/opensearch-php)? 

Or would it make more sense to fork this into a new repo, modify it and name it specifically for this purpose? As far as I could find there are no implementations offering this for opensearch-php and it is also not included in that library.

**Comment by jeskew** [comment]
Did you encounter any incompatibilities? I tested that library, but it looks like the code should be compatible.

**Comment by remyflier** [comment]
My wording could be a bit better :-)   

After your comment I've looked at it again and thought a bit more about it. As far as I've read about Opensearch they intent to keep Opensearch (and with that I expect the opensearch-php library) as compatible with Elasticsearch as possible. 

If so it looks like this package is already fully compatible with both libraries and usable for `opensearch-php` if we supply the handler closure from the Opensearch ClientBuilder. 

That would make the example as follows:
```php
use Aws\ElasticsearchService\ElasticsearchPhpHandler;
use Opensearch\ClientBuilder;

// Create a handler (with the region of your Amazon Opensearch Service domain)
$handler = new ElasticsearchPhpHandler('us-west-2', null, ClientBuilder::defaultHandler());

// Use this handler to create an Opensearch-PHP client
$client = ClientBuilder::create()
    ->setHandler($handler)
    ->setHosts(['https://search-foo-3gn4utxfus5cqpn89go4z5lbsm.us-west-2.es.amazonaws.com:443'])
    ->build();
```

For this example it would only mean that the elasticsearch-php library is still required as a dependency but unused. I feel like this is not ideal.

So the question is more; Do you see any value in making a version of this package which is independent of either search library (or accepting a PR to do so). In practice this would mean removing the default handler, changing the documentation and moving `elasticsearch-php` and `opensearch-php` to the suggests key in composer.json.   It would also mean the name of this package not fully fits the purpose anymore, as it's not specifically Elasticsearch anymore. I'm not really sure how relevant this is.

What do you think?

**Comment by remyflier** [comment]
And to add why I'd rather stay away from the `elasticsearch-php` library while working with AWS Opensearch is because of the seemingly incompatibilities introduced in recent versions of the elasticsearch-php library. 

I''m not 100% sure if the php library is also affected but I'd rather not find out. 

See: https://www.divyanshiinfotech.com/elastic-hits-back-at-opensearch-making-client-libraries-incompatible-with-amazon-led-open-source-fork/

**Comment by remyflier** [comment]
One more comment to solve something I've mentioned earlier when using this package as-is with opensearch-php:

> it would only mean that the elasticsearch-php library is still required as a dependency but unused

We could solve this a bit hacky using the `replace` key in composer.json which prevents composer from installing the elasticsearch library. It's not really a 1-on-1 replacement but with the option of the handler closure as an argument it could act as one.
```
    "require": {
        "opensearch-project/opensearch-php": "^1.0"
    },
    "replace": {
        "elasticsearch/elasticsearch":"*"
    },
```

**Comment by jeskew** [comment]
That makes sense. The best way to remove the elasticsearch-php dependency is probably to copy the defaultHandler function into this library.

**Comment by remyflier** [comment]
I'll have a look at it. Thanks!

**Comment by jeskew** [comment]
Opensearch-php now has an integrated SigV4 signer.
