### ISSUE TITLE
Integration directly into Opensearch-PHP

### ISSUE THREAD

**Issue by shyim** [jeskew/amazon-es-php#30]
Hey,

I am the maintainer of Opensearch-PHP and we want to [implement exactly the same into the SDK directly](https://github.com/opensearch-project/opensearch-clients/issues/22). As you have invested time already into this topic and made it compatible even with this SDK, do you interest porting it directly into the library?

If not I would look myself how to integrate it properly. Anyway thanks for building this 💙

**Comment by jeskew** [comment]
That makes sense to me. V4 signing is built directly into Elastica, and it's a fairly small bit of logic. Integration directly in Opensearch-PHP would require that library to take a direct dependency on the AWS SDK for PHP. Would you have any issue with that?

**Comment by shyim** [comment]
Optional dependency would work also, or 🤔. Just throw an exception if the required class is missing.

Maybe https://github.com/async-aws/core/blob/master/src/Signer/SignerV4.php would work also 🤔 . It is much smaller

**Comment by jeskew** [comment]
I opened a PR for this at https://github.com/opensearch-project/opensearch-php/pull/63
