### ISSUE TITLE
"No alive nodes found in your cluster" when checking for index existence

### ISSUE THREAD

**Issue by tsufurukawa** [jeskew/amazon-es-php#4]
Hi! The setup I have is identical to what's described under "Basic Usage" in the documentation. The handler is loading credentials from env variables. In my code, I'm checking for index existence by `$client->indices()->exists($params)`. Strangely this results in a `Elasticsearch\Common\Exceptions\NoNodesAvailableException with message 'No alive nodes found in your cluster'` error.

All other function calls, including creating index, deleting index, searching, adding mapping, work as expected but it's just this existence call that fails. Haven't had too much time to look into this issue, but was wondering if anyone has experienced something similar and if this might be an issue with this library? If I make the same function call against a local ES server and not AWS ES then it works.

Any insight is appreciated. Thanks!

**Comment by jeskew** [comment]
This library shouldn't affect any particular `elasticsearch-php` operation, as all it does is sign every HTTP request sent. Have you tried asking on the [AWS Elasticsearch Service developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=200) about IAM authentication on index reads? This could be related to #3, but a fix would need to come from the AWS Elasticsearch Service and not from this library.

**Comment by tsufurukawa** [comment]
Ok great that's what I figured. Thanks!

**Comment by dajjen** [comment]
Hi I have the exact same error as you describe. Did you figure it out?
I have tried to debug this error but can't find any data which points me in the right direction. Seems like I have connection to ES cause I can do all other function calls to ES but this ->exists() through this exception
Please write back if you figure it out tsufurukawa

**Comment by victorwelling** [comment]
@dajjen: I think #10 might solve your problem.

**Comment by jcrawford** [comment]
I am trying to create an index so that i can repopulate ElasticSearch however I am getting an error that there are no alive nodes in my cluster.  When I check the status in AWS everything looks fine.  I am using `version 0.2.3` of amazon-es-php and I am using ElasticSearch 2.3.  I checked #10 but it appears that should be in 0.2.3 so I am not sure why I am still receiving this error

```php
if(!$this->getClient()->indices()->exists(['index' => 'myindex'])) {
            $this->getClient()->indices()->create([
                'index' =>'myindex'
                'body' => [
                    'analysis' => [
                        'analyzer' => [
                            'synonym' => [
                                'type' => 'custom',
                                'tokenizer' => 'standard',
                                'filter' => ['synonym']
                            ],
                            'snowball' => [
                                'type' => 'custom',
                                'tokenizer' => 'standard',
                                'filter' => ['snowball']
                            ]
                        ],
                        'filter' => [
                            'synonym' => [
                                'type' => 'synonym',
                                'ignore_case' => true,
                                'synonyms' => [
                                    'trailer, hauler, stacker',
                                    'toterhome, hauler, rv',
                                    'chevy, chevrolet, chev',
                                    'dodge, mopar',
                                    'racecar, race car',
                                    'modified, mod',
                                    'nitro, nitrous, nos',
                                    'feet, foot',
                                    'covered, enclosed',
                                    'mustang, stang',
                                    'barracuda , cuda',
                                    'bwm, bimmer, beamer, beemer',
                                    'volkswagen, volkswagon, vw, vdub',
                                    'van, minivan',
                                    'camaro, camero',
                                    'small block chevy, sbc',
                                    'camshaft, cams, cam',
                                    'automatic, auto',
                                ]
                            ]
                        ]
                    ]
                ]
            ]);
        }
```
