### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by antpuleo2586** [jeskew/amazon-es-php#7]
Hi

I can see that you've already fixed an issue with AWS Elastic Search, where `host` was renamed to `Host` in `v5.3.2` 🤦‍♂️ 

Would you be so kind as to add a release for this please?
We depend on your package and ES is no longer working for us now :(

Thanks and great project!

Antonio

**Comment by jeskew** [comment]
Thanks for the reminder. Just pushed up [v0.2.1](https://github.com/jeskew/amazon-es-php/releases/tag/0.2.1), which includes the fix from #6.
